### PR TITLE
ACES lib and utility files restructure and rename

### PR DESCRIPTION
**Pull request by scottdyer**
The utilities directory contained CTL transforms identified as 'ACESlib' files. This is somewhat of a misnomer, as many of these files labeled 'ACESlib' are actually utility files designed for being run from the command line, e.g. Adjust_Exposure or the Lin_2_Log2 shaper functions. This commit creates a separate 'lib' directory, relocates the actual ACESlib files to there, and then renames utility files in the utilities directory with a more descriptive prefix of 'ACESutil'.

In summary, this pull request:
* relocates 'ACESlib' files to a new lib directory
* renames ACES utility transforms in the utilities subdirectory by changing the prefix from 'ACESlib' to the new 'ACESutil' prefix
* updates any import statements in ACES transforms to reflect the aformentioned file renaming to 'ACESutil'
* makes minor updates to ACES documentation to include the new 'ACESutil' prefix

Note: Users should add `/aces-dev/transforms/ctl/lib` to the colon separated list that resides in their CTL_MODULE_PATH environment variable.

### CODE REVIEW

**Comment by aforsythe** [comment]
Scott,

Per your description in your pull request message shouldn’t ACESutil.Utilities.a1.0.1.ctl and ACESutil.Utilities_Color.a1.0.1.ctl be in the lib directory as they don’t contain a main function?

I’d be open to a rename of the files as  ACESlib.Utilities.a1.0.1.ctl and ACESlib.Utilities_Color.a1.0.1.ctl might possible be a little confusing.

Alex

On November 10, 2015 at 2:48:51 PM, Scott Dyer (notifications@github.com) wrote:
> The utilities directory contained CTL transforms identified as 'ACESlib' files. This
> is somewhat of a misnomer, as many of these files labeled 'ACESlib' are actually utility
> files designed for being run from the command line, e.g. Adjust_Exposure or the Lin_2_Log2
> shaper functions. This commit creates a separate 'lib' directory, relocates the actual
> ACESlib files to there, and then renames utility files in the utilities directory with
> a more descriptive prefix of 'ACESutil'.
>
> In summary, this pull request:
> * relocates 'ACESlib' files to a new lib directory
> * renames ACES utility transforms in the utilities subdirectory by changing the prefix
> from 'ACESlib' to the new 'ACESutil' prefix
> * updates any import statements in ACES transforms to reflect the aformentioned file
> renaming to 'ACESutil'
> * makes minor updates to ACES documentation to include the new 'ACESutil' prefix
>
> Note: Users should add `/aces-dev/transforms/ctl/lib` to the colon separated list
> that resides in their CTL_MODULE_PATH environment variable.
> You can view, comment on, or merge this pull request online at:
>
> https://github.com/ampas/aces-dev/pull/74
>
> -- Commit Summary --
>
> * move 'ACESlib' files to lib directory and change prefix for utility files to 'ACESutil'
> * update S-2014-002 to reflect new type prefix of 'ACESutil'
>
> -- File Changes --
>
> M documents/LaTeX/S-2014-002/S-2014-002.tex (4)
> M documents/LaTeX/S-2014-002/histanddocs.tex (2)
> M documents/LaTeX/S-2014-002/sec-specification.tex (5)
> R transforms/ctl/lib/ACESlib.ODT_Common.a1.0.1.ctl (0)
> R transforms/ctl/lib/ACESlib.RRT_Common.a1.0.1.ctl (0)
> R transforms/ctl/lib/ACESlib.Tonescales.a1.0.1.ctl (0)
> R transforms/ctl/lib/ACESlib.Transform_Common.a1.0.1.ctl (4)
> M transforms/ctl/odt/dcdm/InvODT.Academy.DCDM.a1.0.1.ctl (2)
> M transforms/ctl/odt/dcdm/ODT.Academy.DCDM.a1.0.1.ctl (2)
> M transforms/ctl/odt/dcdm/ODT.Academy.DCDM_P3D60.a1.0.1.ctl (2)
> M transforms/ctl/odt/hdr_st2084/InvODT.Academy.P3D60_ST2084_1000nits.a1.0.1.ctl
> (2)
> M transforms/ctl/odt/hdr_st2084/InvODT.Academy.P3D60_ST2084_2000nits.a1.0.1.ctl
> (2)
> M transforms/ctl/odt/hdr_st2084/InvODT.Academy.P3D60_ST2084_4000nits.a1.0.1.ctl
> (2)
> M transforms/ctl/odt/hdr_st2084/InvODT.Academy.Rec2020_ST2084_1000nits.a1.0.1.ctl
> (2)
> M transforms/ctl/odt/hdr_st2084/ODT.Academy.P3D60_ST2084_1000nits.a1.0.1.ctl
> (2)
> M transforms/ctl/odt/hdr_st2084/ODT.Academy.P3D60_ST2084_2000nits.a1.0.1.ctl
> (2)
> M transforms/ctl/odt/hdr_st2084/ODT.Academy.P3D60_ST2084_4000nits.a1.0.1.ctl
> (2)
> M transforms/ctl/odt/hdr_st2084/ODT.Academy.Rec2020_ST2084_1000nits.a1.0.1.ctl
> (2)
> M transforms/ctl/odt/p3/InvODT.Academy.P3D60_48nits.a1.0.1.ctl (2)
> M transforms/ctl/odt/p3/InvODT.Academy.P3DCI_48nits.a1.0.1.ctl (2)
> M transforms/ctl/odt/p3/ODT.Academy.P3D60_48nits.a1.0.1.ctl (2)
> M transforms/ctl/odt/p3/ODT.Academy.P3DCI_48nits.a1.0.1.ctl (2)
> M transforms/ctl/odt/rec2020/InvODT.Academy.Rec2020_100nits_dim.a1.0.1.ctl
> (2)
> M transforms/ctl/odt/rec2020/ODT.Academy.Rec2020_100nits_dim.a1.0.1.ctl (2)
> M transforms/ctl/odt/rec709/InvODT.Academy.Rec709_100nits_dim.a1.0.1.ctl
> (2)
> M transforms/ctl/odt/rec709/InvODT.Academy.Rec709_D60sim_100nits_dim.a1.0.1.ctl
> (2)
> M transforms/ctl/odt/rec709/ODT.Academy.Rec709_100nits_dim.a1.0.1.ctl (2)
> M transforms/ctl/odt/rec709/ODT.Academy.Rec709_D60sim_100nits_dim.a1.0.1.ctl
> (2)
> M transforms/ctl/odt/rgbMonitor/InvODT.Academy.RGBmonitor_D60sim_100nits_dim.a1.0.1.ctl
> (2)
> M transforms/ctl/odt/rgbMonitor/ODT.Academy.RGBmonitor_D60sim_100nits_dim.a1.0.1.ctl
> (2)
> M transforms/ctl/rrt/InvRRT.a1.0.1.ctl (2)
> M transforms/ctl/rrt/RRT.a1.0.1.ctl (2)
> R transforms/ctl/utilities/ACESutil.Adjust_Exposure.a1.0.1.ctl (2)
> R transforms/ctl/utilities/ACESutil.DolbyPQ_to_Lin.a1.0.1.ctl (4)
> R transforms/ctl/utilities/ACESutil.Lin_to_DolbyPQ.a1.0.1.ctl (4)
> R transforms/ctl/utilities/ACESutil.Lin_to_Log2_param.a1.0.1.ctl (2)
> R transforms/ctl/utilities/ACESutil.Lin_to_OCIOshaper_param.a1.0.1.ctl (4)
> R transforms/ctl/utilities/ACESutil.Log2_to_Lin_param.a1.0.1.ctl (2)
> R transforms/ctl/utilities/ACESutil.OCIOshaper_to_Lin_param.a1.0.1.ctl (4)
> R transforms/ctl/utilities/ACESutil.Unity.a1.0.1.ctl (2)
> R transforms/ctl/utilities/ACESutil.Utilities.a1.0.1.ctl (2)
> R transforms/ctl/utilities/ACESutil.Utilities_Color.a1.0.1.ctl (6)
>
> -- Patch Links --
>
> https://github.com/ampas/aces-dev/pull/74.patch
> https://github.com/ampas/aces-dev/pull/74.diff
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/ampas/aces-dev/pull/74
>

[?]<http://www.oscars.org>


Alex Forsythe
Image Engineering Manager


Academy of Motion Picture Arts and Sciences
Science & Technology Council
1313 Vine Street • Hollywood, CA 90028


323.817.4170 • aforsythe@oscars.org<mailto:aforsythe@oscars.org>

**Comment by scottdyer** [comment]
Technically, yes, you are right.

But the functions supplied in utilities are not specific to ACES. That's why I wanted to drop the prefix all together. I use them for non-ACES things. The "non-main" function construct as criteria for lib vs util is new. Utilities used to be exactly that - utilities. The problem that caused all of this was the introduction of the ACESlib prefix being used for everything in ACES 1.0. Prior to that, everything made sense.

**Comment by aforsythe** [comment]
What the actual directory/prefix are seems secondary to the point that CTL modules without main functions that can be called directly (e.g. Utilities.a1.0.1.ctl, ODT_Common.a1.0.1.ctl, etc.) should be separated from those that do but don’t fit other places in the directory structure (e.g. Adjust_Exposure.a1.0.1.ctl, Lin_to_OCIOshaper_param.a1.0.1.ctl , etc.).

Idk … Just my 2¢

On November 10, 2015 at 3:13:04 PM, Scott Dyer (notifications@github.com) wrote:
> Technically, yes, you are right.
>
> But the functions supplied in utilities are not specific to ACES. That's why I wanted
> to drop the prefix all together. I use them for non-ACES things. The "non-main" function
> construct as criteria for lib vs util is new. Utilities used to be exactly that - utilities.
> The problem that caused all of this was the introduction of the ACESlib prefix being used
> for everything in ACES 1.0. Prior to that, everything made sense.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/ampas/aces-dev/pull/74#issuecomment-155598156

[?]<http://www.oscars.org>


Alex Forsythe
Image Engineering Manager


Academy of Motion Picture Arts and Sciences
Science & Technology Council
1313 Vine Street • Hollywood, CA 90028


323.817.4170 • aforsythe@oscars.org<mailto:aforsythe@oscars.org>

**Comment by scottdyer** [comment]
@aforsythe I've changed everything back to the way it was. Is that better?

**Comment by aforsythe** [comment]
I personally think that’s more in line with initial change request.  Thanks!

Alex


On November 10, 2015 at 3:40:57 PM, Scott Dyer (notifications@github.com) wrote:
> @aforsythe I've changed everything back to the way it was. Is that better?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/ampas/aces-dev/pull/74#issuecomment-155603585

[?]<http://www.oscars.org>


Alex Forsythe
Image Engineering Manager


Academy of Motion Picture Arts and Sciences
Science & Technology Council
1313 Vine Street • Hollywood, CA 90028


323.817.4170 • aforsythe@oscars.org<mailto:aforsythe@oscars.org>

**Comment by scottdyer** [comment]
All fixes squash merged into dev with commit 583f427

**Pull request closed without merging**
