### PR TITLE
adds RGBmonitor D65 forward and inverse ODTs

### PR DESCRIPTION
**Pull request by aforsythe**

### CODE REVIEW

**Comment by scottdyer** [comment]
I've added some prep work to images/README to describe the golden images that will be added when this branch is merged. Could you checkout my branch and if you agree with my changes ff your branch and push to your remote to update the PR?

**Comment by KevinJW** [comment]
Being fussy I wondered what the comments relating to the DCI white were doing in the ODT line 101...

Kevin

**Comment by scottdyer** [comment]
@KevinJW, is absolutely right. The small scaling done for D60 simulation should not be in there in the forward or inverse. 

In addition to my previous additions, I've added the changes Kevin pointed out. I did a cleanup to the branch and opened a new PR #85 with my changes. I will close this one and we will use the other moving forward.

**Comment by aforsythe** [comment]
Awesome!   Exactly the way pull request and code review are supposed to work.  Thanks so much @KevinJW and @scottdyer

**Pull request closed without merging**
